title: 'Simply Logical:<br>Intelligent Reasoning by Example'
author: >
  <a href="mailto:Peter.Flach@bristol.ac.uk">Peter Flach</a> and
  <a href="mailto:K.Sokol@bristol.ac.uk">Kacper Sokol</a>,
  University of Bristol, United Kingdom
copyright: '2015–2020'
logo: src/img/SL.svg

exclude_patterns: [README.md, .DS_Store, __pycache__, _ext]

execute:
  execute_notebooks: off

html:
  favicon: src/img/favicon.ico
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  extra_navbar: >
    <a href="https://doi.org/10.5281/zenodo.1156977"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.1156977.svg" alt="DOI"></a>
  extra_footer: >
    This book discusses methods to implement intelligent reasoning by means of
    Prolog programs.
    The book is written from the shared viewpoints of Computational Logic,
    which aims at automating various kinds of reasoning, and Artificial
    Intelligence, which seeks to implement aspects of intelligent behaviour on
    a computer.
  google_analytics_id: UA-112595762-2
  home_page_in_navbar: true

parse:
  myst_extended_syntax: true

latex:
  latex_engine: pdflatex

repository:
  url: https://github.com/simply-logical/simply-logical

sphinx:
  local_extensions:
    sl: _ext
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    sl_code_directory: /src/code/
    sl_swish_url: https://swish.simply-logical.space/
